// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWQvnj4GdfMV1sHL1VjySg5CchWUyzMMA',
    appId: '1:16270499581:web:37353ab6b07e8cd9cda894',
    messagingSenderId: '16270499581',
    projectId: 'music-app-0257',
    authDomain: 'music-app-0257.firebaseapp.com',
    storageBucket: 'music-app-0257.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEzNodSNP1RTAc5aXo9Qu-pJZxSothQz8',
    appId: '1:16270499581:android:2a2048f1b0aba12bcda894',
    messagingSenderId: '16270499581',
    projectId: 'music-app-0257',
    storageBucket: 'music-app-0257.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx8DhS4iC2QnHu95jZn7EESIGj0YrxH0Y',
    appId: '1:16270499581:ios:49bf6f60dc3824cdcda894',
    messagingSenderId: '16270499581',
    projectId: 'music-app-0257',
    storageBucket: 'music-app-0257.appspot.com',
    iosClientId: '16270499581-t957havvfpcn9s1h1uujnu6ceaq2p2lj.apps.googleusercontent.com',
    iosBundleId: 'com.example.luna',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx8DhS4iC2QnHu95jZn7EESIGj0YrxH0Y',
    appId: '1:16270499581:ios:49bf6f60dc3824cdcda894',
    messagingSenderId: '16270499581',
    projectId: 'music-app-0257',
    storageBucket: 'music-app-0257.appspot.com',
    iosClientId: '16270499581-t957havvfpcn9s1h1uujnu6ceaq2p2lj.apps.googleusercontent.com',
    iosBundleId: 'com.example.luna',
  );
}
